# platform :ios, '8.0'

target ‘runoob’ do
  use_frameworks!

  pod 'SDWebImage', '~> 3.8.1'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'MJRefresh', '~> 3.1.9'
  pod 'MWPhotoBrowser', '~> 2.1.2'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'PNChart', '~> 0.8.9'
  pod 'WebViewJavascriptBridge', '~> 6.0.2'

end
